---
# Rift role tasks
# This role handles core Rift functionality and setup

- name: Create Rift configuration directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /etc/rift
    - /etc/rift/config
    - /var/log/rift

- name: Install Rift dependencies
  dnf:
    name:
      - python3-pip
      - python3-setuptools
      - python3-devel
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Python packages
  pip:
    name:
      - ansible-core>=2.9
      - molecule
      - molecule-podman
    state: present
    executable: pip3

- name: Ensure Rift service is enabled
  systemd:
    name: rift
    enabled: yes
    state: started
  when: ansible_service_mgr == 'systemd' 