---
# Rift deployment playbook
- name: Configure base system
  hosts: all
  become: true
  roles:
    - common

- name: Configure cloud-specific requirements
  hosts: cloud
  become: true
  roles:
    - cloud

- name: Deploy Rift
  hosts: rift_servers
  become: true
  roles:
    - rift
  vars:
    rift_version: "{{ lookup('file', 'VERSION') | trim }}"
    deployment_type: "{{ deployment_type | default('standard') }}" 