---
- name: Verify Rift Installation
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Check rift command exists
  command: which rift
  register: rift_path
      changed_when: false
      failed_when: false

    - name: Display rift path
  debug:
    msg: "Rift installed at: {{ rift_path.stdout }}"

    - name: Get rift version
  command: rift version
  register: rift_version
      changed_when: false

    - name: Display rift version
  debug:
    msg: "{{ rift_version.stdout_lines }}"

    - name: Verify required directories
      stat:
        path: "{{ item }}"
      register: dir_check
      loop:
        - /usr/share/rift
        - /usr/share/rift/playbooks
        - /usr/share/rift/roles
        - /usr/share/rift/inventory
        - /usr/share/rift/tools

    - name: Display directory check results
      debug:
        msg: "{{ item.stat.exists }}"
      loop: "{{ dir_check.results }}"

    - name: List installed roles
      find:
        paths: /usr/share/rift/roles
        patterns: "*.yml"
      register: roles_list

    - name: Display installed roles
      debug:
        msg: "Installed roles: {{ roles_list.files | map(attribute='path') | map('basename') | list }}"

    - name: Verify ansible.cfg
      stat:
        path: /usr/share/rift/ansible.cfg
      register: ansible_cfg

    - name: Display ansible.cfg status
      debug:
        msg: "ansible.cfg exists: {{ ansible_cfg.stat.exists }}" 