name: Build RPM Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-rpm:
    strategy:
      matrix:
        distro: [rhel9, rocky9]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for release notes

      - name: Set up RPM build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm rpm2cpio cpio alien

      - name: Create RPM build directories
        run: |
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

      - name: Create source tarball
        run: |
          # Get current directory
          WORKSPACE_DIR=$(pwd)
          echo "Workspace directory: ${WORKSPACE_DIR}"
          
          # Read and clean version string
          VERSION=$(cat VERSION | tr -d '[:space:]')
          echo "Creating tarball for version: '${VERSION}'"
          
          # Create temporary directory in workspace
          TEMP_DIR=$(mktemp -d)
          echo "Created temporary directory: ${TEMP_DIR}"
          
          # Create versioned directory
          VERSION_DIR="${TEMP_DIR}/chasm-${VERSION}"
          mkdir -p "${VERSION_DIR}"
          echo "Created version directory: ${VERSION_DIR}"
          
          # Copy all files except .git and temp directory
          echo "Copying files to version directory..."
          find "${WORKSPACE_DIR}" -maxdepth 1 -not -name '.' -not -name '..' -not -name '.git' -not -name "${TEMP_DIR##*/}" -exec cp -rv {} "${VERSION_DIR}/" \;
          
          # Verify files were copied
          echo "Verifying files in version directory..."
          ls -la "${VERSION_DIR}"
          
          # Create the tarball
          echo "Creating tarball..."
          cd "${TEMP_DIR}"
          echo "Current directory: $(pwd)"
          echo "Contents of current directory:"
          ls -la
          
          TARBALL_PATH="${HOME}/rpmbuild/SOURCES/chasm-${VERSION}.tar.gz"
          echo "Creating tarball at: ${TARBALL_PATH}"
          
          tar -czvf "${TARBALL_PATH}" "chasm-${VERSION}"
          TAR_EXIT_CODE=$?
          echo "Tar exit code: ${TAR_EXIT_CODE}"
          
          # Verify tarball was created
          echo "Verifying tarball..."
          ls -l "${TARBALL_PATH}"
          
          # Clean up
          cd "${WORKSPACE_DIR}"
          rm -rf "${TEMP_DIR}"

      - name: Update spec file version
        run: |
          # Read and clean version string
          VERSION=$(cat VERSION | tr -d '[:space:]')
          echo "Updating spec file with version: '${VERSION}'"
          
          # Update version in spec file
          sed -i "s/^Version:.*/Version:        ${VERSION}/" chasm.spec
          
          # Copy spec file to SPECS directory
          cp chasm.spec ~/rpmbuild/SPECS/
          
          # Verify spec file
          echo "Verifying spec file contents:"
          cat ~/rpmbuild/SPECS/chasm.spec
          
          # Verify source tarball exists
          echo "Verifying source tarball exists:"
          ls -l "${HOME}/rpmbuild/SOURCES/chasm-${VERSION}.tar.gz"

      - name: Build RPM package
        run: |
          cd ~/rpmbuild/SPECS
          rpmbuild --define "_topdir $HOME/rpmbuild" -bb chasm.spec

      - name: Generate release notes
        id: release_notes
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          # Get the previous tag
          PREV_TAG=$(git describe --tags --abbrev=0 ${{ github.ref }}^ 2>/dev/null || echo "")
          
          if [ -z "$PREV_TAG" ]; then
            # If no previous tag, get all commits
            RELEASE_NOTES=$(git log --pretty=format:"* %s (%h)" ${{ github.ref }})
          else
            # Get commits between tags
            RELEASE_NOTES=$(git log --pretty=format:"* %s (%h)" $PREV_TAG..${{ github.ref }})
          fi
          
          # Escape newlines for GitHub Actions
          RELEASE_NOTES="${RELEASE_NOTES//'%'/'%25'}"
          RELEASE_NOTES="${RELEASE_NOTES//$'\n'/'%0A'}"
          RELEASE_NOTES="${RELEASE_NOTES//$'\r'/'%0D'}"
          
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          echo "## What's Changed" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "$RELEASE_NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v4
        with:
          name: chasm-rpm-${{ matrix.distro }}
          path: ~/rpmbuild/RPMS/noarch/*.rpm

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ~/rpmbuild/RPMS/noarch/*.rpm
          body: ${{ steps.release_notes.outputs.notes }}
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-rpm:
    needs: build-rpm
    runs-on: ubuntu-latest
    steps:
      - name: Download RHEL RPM artifact
        uses: actions/download-artifact@v4
        with:
          name: chasm-rpm-rhel9
          path: ./rhel
          pattern: '*.rpm'
          merge-multiple: true

      - name: Download Rocky Linux RPM artifact
        uses: actions/download-artifact@v4
        with:
          name: chasm-rpm-rocky9
          path: ./rocky
          pattern: '*.rpm'
          merge-multiple: true

      - name: List downloaded artifacts
        run: |
          echo "Contents of rhel directory:"
          ls -la ./rhel || true
          echo "Contents of rocky directory:"
          ls -la ./rocky || true

      - name: Run basic RPM tests
        run: |
          # Create a temporary directory for testing
          TEST_DIR=$(mktemp -d)
          cd "$TEST_DIR"
          
          # Copy RPMs to test directory if they exist
          if [ -d "$GITHUB_WORKSPACE/rhel" ] && ls "$GITHUB_WORKSPACE/rhel"/*.rpm 1> /dev/null 2>&1; then
              echo "Copying RHEL RPMs..."
              cp "$GITHUB_WORKSPACE/rhel"/*.rpm .
          else
              echo "No RHEL RPMs found"
          fi
          
          if [ -d "$GITHUB_WORKSPACE/rocky" ] && ls "$GITHUB_WORKSPACE/rocky"/*.rpm 1> /dev/null 2>&1; then
              echo "Copying Rocky Linux RPMs..."
              cp "$GITHUB_WORKSPACE/rocky"/*.rpm .
          else
              echo "No Rocky Linux RPMs found"
          fi
          
          # Verify RPMs are present
          if ! ls *.rpm 1> /dev/null 2>&1; then
              echo "Error: No RPM files found in test directory"
              exit 1
          fi
          
          # Create a container for testing
          if command -v podman &> /dev/null; then
              CONTAINER_CMD=podman
          else
              CONTAINER_CMD=docker
          fi
          
          # Test on Rocky Linux 9
          echo "Testing on Rocky Linux 9..."
          $CONTAINER_CMD run --rm -v "$TEST_DIR:/rpms" \
              -w /rpms quay.io/rockylinux/rockylinux:9 \
              bash -c '
                  dnf -y install epel-release
                  dnf -y install python3 python3-pip
                  dnf -y install ansible-core
                  dnf -y install /rpms/*.rpm
                  chasm test
              '
          
          # Test on RHEL 9
          echo "Testing on RHEL 9..."
          $CONTAINER_CMD run --rm -v "$TEST_DIR:/rpms" \
              -w /rpms registry.access.redhat.com/ubi9/ubi:latest \
              bash -c '
                  # Enable CRB repository
                  dnf -y install dnf-utils
                  dnf config-manager --set-enabled crb
                  
                  # Install EPEL
                  dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
                  
                  # Install Python and pip
                  dnf -y install python3 python3-pip
                  
                  # Install ansible-core via pip
                  pip3 install "ansible-core>=2.9"
                  
                  # Install Chasm RPM without dependency checking
                  rpm -ivh --nodeps /rpms/*.rpm
                  
                  # Run tests
                  chasm test
              '
          
          # Clean up
          cd "$GITHUB_WORKSPACE"
          rm -rf "$TEST_DIR" 