name: Shared RPM Test

on:
  workflow_call:
    inputs:
      rpm_path:
        description: "Path to the RPM to test"
        required: true
        type: string
      distro:
        description: "Distribution to test on (rhel9, rocky9)"
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.distro == 'rocky9' && 'rockylinux:9' || 'redhat/ubi9' }}
    steps:
      - name: Install dependencies
        run: |
          # Enable required repositories
          if [ "${{ inputs.distro }}" = "rhel9" ]; then
            dnf -y install dnf-utils
            dnf config-manager --set-enabled crb
            dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
          else
            dnf -y install epel-release
          fi
          
          # Install base dependencies
          dnf -y install python3 python3-pip python3-sphinx python3-sphinx-rtd-theme

      - name: Install and test RPM
        run: |
          # Install the RPM
          rpm -ivh "${{ inputs.rpm_path }}"
          
          # Test chasm command
          chasm version || exit 1 