name: Shared RPM Test

on:
  workflow_call:
    inputs:
      rpm_path:
        description: "Path to the RPM to test"
        required: true
        type: string
      distro:
        description: "Distribution to test on (rhel9, rocky9)"
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.distro == 'rocky9' && 'rockylinux:9' || 'redhat/ubi9' }}
    steps:
      - name: Install dependencies
        run: |
          # Enable required repositories
          if [ "${{ inputs.distro }}" = "rhel9" ]; then
            # For RHEL UBI, install dnf-utils first
            dnf -y install dnf-utils
            
            # Try to enable CRB (CodeReady Builder) if available
            # UBI containers may not have these repos, so don't fail on error
            dnf config-manager --set-enabled codeready-builder-for-rhel-9-$(arch) 2>/dev/null || \
            dnf config-manager --set-enabled crb 2>/dev/null || \
            echo "CRB repository not available in UBI container, continuing without it"
            
            # Install EPEL RPM directly (this should work in UBI)
            dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm || \
            echo "EPEL installation failed, continuing without it"
            
            # Clean and update metadata
            dnf clean all
            dnf makecache
          else
            # For Rocky Linux - enable EPEL and CRB
            dnf -y install epel-release
            dnf config-manager --set-enabled crb
            dnf clean all
            dnf makecache
          fi
          
          # Install base dependencies
          dnf -y install python3 python3-pip

      - name: Install and test RPM
        run: |
          # Install the RPM
          rpm -ivh "${{ inputs.rpm_path }}"
          
          # Test rift command
          rift version || exit 1 