name: Test Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-rpm:
    strategy:
      matrix:
        distro: [rhel9, rocky9]
    uses: ./.github/workflows/shared-rpm-build.yml
    with:
      version_type: dev
      distro: ${{ matrix.distro }}

  test-rpm:
    needs: build-rpm
    strategy:
      matrix:
        distro: [rhel9, rocky9]
    uses: ./.github/workflows/shared-rpm-test.yml
    with:
      distro: ${{ matrix.distro }} 